calendar = Calendar.create!(day: 1)

Item.create!(item_key: 0, information: "Weeds/0/-1/Basic/Weeds/A bunch of obnoxious weeds.")
Item.create!(item_key: 2, information: "Stone/0/-300/Basic/Stone/A useful material when broken with the Pickaxe.")
Item.create!(item_key: 4, information: "Stone/0/-300/Basic/Stone/A useful material when chopped with the axe.")
Item.create!(item_key: 16, information: "Wild Horseradish/50/5/Basic -81/Wild Horseradish/A spicy root found in the spring.")
Item.create!(item_key: 18, information: "Daffodil/30/0/Basic -81/Daffodil/A traditional spring flower that makes a nice gift.")
Item.create!(item_key: 20, information: "Leek/60/16/Basic -81/Leek/A tasty relative of the onion.")
Item.create!(item_key: 22, information: "Dandelion/40/10/Basic -81/Dandelion/Not the prettiest flower, but the leaves make a good salad.")
Item.create!(item_key: 24, information: "Parsnip/35/10/Basic -75/Parsnip/A spring tuber closely related to the carrot. It has an earthy taste and is full of nutrients.")
Item.create!(item_key: 30, information: "Lumber/2/10/Basic/Lumber/A versatile resource used for building and fuel.")
Item.create!(item_key: 60, information: "Emerald/250/-300/Minerals -2/Emerald/A precious stone with a brilliant green color.")
Item.create!(item_key: 62, information: "Aquamarine/180/-300/Minerals -2/Aquamarine/A shimmery blue-green gem .")
Item.create!(item_key: 64, information: "Ruby/250/-300/Minerals -2/Ruby/A precious stone that is sought after for its rich color and beautiful luster.")
Item.create!(item_key: 66, information: "Amethyst/100/-300/Minerals -2/Amethyst/A purple variant of quartz.")
Item.create!(item_key: 68, information: "Topaz/80/-300/Minerals -2/Topaz/Fairly common but still prized for its beauty.")
Item.create!(item_key: 70, information: "Jade/200/-300/Minerals -2/Jade/A pale green ornamental stone.")
Item.create!(item_key: 72, information: "Diamond/750/-300/Minerals -2/Diamond/A rare and valuable gem.")
Item.create!(item_key: 74, information: "Prismatic Shard/2000/-300/Minerals -2/Prismatic Shard/A very rare and powerful substance with unknown origins.")
Item.create!(item_key: 75, information: "Stone/50/-300/Basic/Stone/...")
Item.create!(item_key: 76, information: "Stone/50/-300/Basic/Stone/...")
Item.create!(item_key: 77, information: "Stone/50/-300/Basic/Stone/...")
Item.create!(item_key: 78, information: "Cave Carrot/25/12/Basic -81/Cave Carrot/A starchy snack found in caves. It helps miners work longer.")
Item.create!(item_key: 80, information: "Quartz/25/-300/Minerals -2/Quartz/A clear crystal commonly found in caves and mines.")
Item.create!(item_key: 82, information: "Fire Quartz/100/-300/Minerals -2/Fire Quartz/A glowing red crystal commonly found near hot lava.")
Item.create!(item_key: 84, information: "Frozen Tear/75/-300/Minerals -2/Frozen Tear/A crystal fabled to be the frozen tears of a yeti.")
Item.create!(item_key: 86, information: "Earth Crystal/50/-300/Minerals -2/Earth Crystal/A resinous substance found near the surface.")
Item.create!(item_key: 88, information: "Coconut/100/-300/Basic -79/Coconut/A seed of the coconut palm. It has many culinary uses.")
Item.create!(item_key: 90, information: "Cactus Fruit/75/30/Basic -79/Cactus Fruit/The sweet fruit of the prickly pear cactus.")
Item.create!(item_key: 92, information: "Sap/2/-1/Basic -81/Sap/A fluid obtained from trees.")
Item.create!(item_key: 93, information: "Torch/5/-300/Crafting/Torch/Provides a modest amount of light.")
Item.create!(item_key: 94, information: "Spirit Torch/5/-300/Crafting/Spirit Torch/It's unclear where the blue color comes from...")
Item.create!(item_key: 96, information: "Dwarf Scroll I/1/-300/Arch/Dwarf Scroll I/A yellowed scroll of parchment filled with dwarven script. This one's tied with a red bow.//Set Dwarf 96 97 98 99")
Item.create!(item_key: 97, information: "Dwarf Scroll II/1/-300/Arch/Dwarf Scroll II/A yellowed scroll of parchment filled with dwarven script. This one's tied with a green ribbon.//Set Dwarf 96 97 98 99")
Item.create!(item_key: 98, information: "Dwarf Scroll III/1/-300/Arch/Dwarf Scroll III/A yellowed scroll of parchment filled with dwarven script. This one's tied with a blue rope.//Set Dwarf 96 97 98 99")
Item.create!(item_key: 99, information: "Dwarf Scroll IV/1/-300/Arch/Dwarf Scroll IV/A yellowed scroll of parchment filled with dwarven script. This one's tied with a golden chain.//Set Dwarf 96 97 98 99")
Item.create!(item_key: 100, information: "Chipped Amphora/40/-300/Arch/Chipped Amphora/An ancient vessel made of ceramic material. Used to transport both dry and wet goods./Town .04/Item 3 461")
Item.create!(item_key: 101, information: "Arrowhead/40/-300/Arch/Arrowhead/A crudely fashioned point used for hunting./Mountain .02 Forest .02 BusStop .02/Debris 2 30 14")
Item.create!(item_key: 102, information: "Lost Book/50/-300/asdf/Lost Book/Writings from a wide variety of time periods./Town .05/Note")
Item.create!(item_key: 103, information: "Ancient Doll/60/-300/Arch/Ancient Doll/An ancient doll covered in grime. This doll may have been used as a toy, a decoration, or a prop in some kind of ritual./Mountain .04 Forest .03 BusStop .03 Town .01/Money 1 250")
Item.create!(item_key: 104, information: "Elvish Jewelry/200/-300/Arch/Elvish Jewelry/Dirty but still beautiful. On the side is a flowing script thought by some to be the ancient language of the elves. No Elvish bones have ever been found./Forest .01/Debris 1 20 6")
Item.create!(item_key: 105, information: "Chewing Stick/50/-300/Arch/Chewing Stick/Ancient people chewed on these to keep their teeth clean./Mountain .02 Town .01 Forest .02/Decor 10 28")
Item.create!(item_key: 106, information: "Ornamental Fan/300/-300/Arch/Ornamental Fan/This exquisute fan most likely belonged to a noblewoman. Historians believe that the valley was a popular sixth-era vacation spot for the wealthy./Beach .02 Town .008 Forest .01/Money 1 300")
Item.create!(item_key: 107, information: "Dinosaur Egg/350/-300/Arch/Dinosaur Egg/A giant dino egg... The entire shell is still intact!/Mine .01 Mountain .008/Item 1 107")
Item.create!(item_key: 108, information: "Rare Disc/300/-300/Arch/Rare Disc/A heavy black disc studded with peculiar red stones. When you hold it, you're overwhelmed with a feeling of dread./UndergroundMine .01/Decor 1 29")
Item.create!(item_key: 109, information: "Ancient Sword/100/-300/Arch/Ancient Sword/It's the remains of an ancient sword. Most of the blade has turned to rust, but the hilt is very finely crafted./Forest .01 Mountain .008/Debris 1 30 2")
Item.create!(item_key: 110, information: "Rusty Spoon/25/-300/Arch/Rusty Spoon/A plain old spoon, probably ten years old. Not very interesting./Town .05/Debris 5 30 2")
Item.create!(item_key: 111, information: "Rusty Spur/25/-300/Arch/Rusty Spur/An old spur that was once attached to a cowboy's boot. People must have been raising animals in this area for many generations./Farm .1/Money 1 100")
Item.create!(item_key: 112, information: "Rusty Cog/25/-300/Arch/Rusty Cog/A well preserved cog that must have been part of some ancient machine. This could be dwarven technology./Mountain .05/Debris 1 20 4")
Item.create!(item_key: 113, information: "Chicken Statue/50/-300/Arch/Chicken Statue/It's a statue of a chicken on a bronze base. The ancient people of this area must have been very fond of chickens./Farm .1/Decor 5 31")
Item.create!(item_key: 114, information: "Ancient Seed/5/-300/Arch/Ancient Seed/It's a dry old seed from some ancient plant. By all appearances it's long since dead.../Forest .01 Mountain .01/Seeds 9")
Item.create!(item_key: 115, information: "Prehistoric Tool/50/-300/Arch/Prehistoric Tool/Some kind of gnarly old digging tool./Mountain .03 Forest .03 BusStop .04/Debris 1 30 12")
Item.create!(item_key: 116, information: "Dried Starfish/40/-300/Arch/Dried Starfish/A starfish from the primordial ocean. It's an unusually pristine specimen!/Beach .1/Money 1 200")
Item.create!(item_key: 117, information: "Anchor/100/-300/Arch/Anchor/It may have belonged to ancient pirates./Beach .05/Item 1 289")
Item.create!(item_key: 118, information: "Glass Shards/20/-300/Arch/Glass Shards/A mixture of glass shards smoothed by centuries of ocean surf. These could have belonged to an ancient mosaic or necklace./Beach .1/Item 1 462")
Item.create!(item_key: 119, information: "Bone Flute/100/-300/Arch/Bone Flute/It's a prehistoric wind instrument carved from an animal's bone. It produces an eerie tone./Mountain .01 Forest .01 UndergroundMine .02 Town .005/Recipe 2 Flute_Block 150")
Item.create!(item_key: 120, information: "Prehistoric Handaxe/50/-300/Arch/Prehistoric Handaxe/One of the earliest tools employed by humans. This \"crude\" tool was created by striking one rock with another to form a sharp edge./Mountain .05 Forest .05 BusStop .05/Item 1 294")
Item.create!(item_key: 121, information: "Dwarvish Helm/100/-300/Arch/Dwarvish Helm/It's one of the helmets commonly worn by dwarves. The thick metal plating protects them from falling debris and stalactites./UndergroundMine .01/Debris 1 50 0")
Item.create!(item_key: 122, information: "Dwarf Gadget/200/-300/Arch/Dwarf Gadget/It's a piece of the advanced technology once known to the dwarves. It's still glowing and humming, but you're unable to understand how it works./UndergroundMine .001/Money 1 500")
Item.create!(item_key: 123, information: "Ancient Drum/100/-300/Arch/Ancient Drum/It's a drum made from wood and animal skin. It has a low, reverberating tone./BusStop .01 Forest .01 UndergroundMine .02 Town .005/Recipe 2 Drum_Block 300")
Item.create!(item_key: 124, information: "Golden Mask/500/-300/Arch/Golden Mask/A creepy golden mask probably used in an ancient magic ritual. A socket in the forehead contains a large purple gemstone./Desert .04/Money 1 1000")
Item.create!(item_key: 125, information: "Golden Relic/250/-300/Arch/Golden Relic/It's a golden slab with heiroglyphs and pictures emblazoned onto the front./Desert .08/Debris 1 40 6")
Item.create!(item_key: 126, information: "Strange Doll/1000/-300/Arch/Strange Doll/???/Farm .001 Town .001 Mountain .001 Forest .001 BusStop .001 Beach .001 UndergroundMine .001/Item 1 126")
Item.create!(item_key: 127, information: "Strange Doll/1000/-300/Arch/Strange Doll/???/Farm .001 Town .001 Mountain .001 Forest .001 BusStop .001 Beach .001 UndergroundMine .001/Item 1 127")
Item.create!(item_key: 128, information: "Pufferfish/200/-40/Fish -4/Pufferfish/Inflates when threatened./Day^Summer")
Item.create!(item_key: 129, information: "Anchovy/30/5/Fish -4/Anchovy/A small silver fish found in the ocean./Day Night^Spring Fall")
Item.create!(item_key: 130, information: "Tuna/100/15/Fish -4/Tuna/A large fish that lives in the ocean./Day^Summer Winter")
Item.create!(item_key: 131, information: "Sardine/40/5/Fish -4/Sardine/A common ocean fish./Day^Spring Summer Fall Winter")
Item.create!(item_key: 132, information: "Bream/45/5/Fish -4/Bream/A fairly common river fish that becomes active at night./Night^Spring Summer Fall Winter")
Item.create!(item_key: 136, information: "Largemouth Bass/100/15/Fish -4/Largemouth Bass/A popular fish that lives in lakes./Day^Spring Summer Fall Winter")
Item.create!(item_key: 137, information: "Smallmouth Bass/50/10/Fish -4/Smallmouth Bass/A freshwater fish that is very sensitive to pollution./Day Night^Spring Fall")
Item.create!(item_key: 138, information: "Rainbow Trout/65/10/Fish -4/Rainbow Trout/A freshwater trout with colorful markings./Day^Summer")
Item.create!(item_key: 139, information: "Salmon/75/15/Fish -4/Salmon/Swims upstream to lay its eggs./Day^Fall")
Item.create!(item_key: 140, information: "Walleye/105/12/Fish -4/Walleye/A freshwater fish caught at night./Night^Fall Winter")
Item.create!(item_key: 141, information: "Perch/55/10/Fish -4/Perch/A freshwater fish of the winter./Day Night^Winter")
Item.create!(item_key: 142, information: "Carp/30/5/Fish -4/Carp/A common pond fish./Day Night^Spring Summer Fall")
Item.create!(item_key: 143, information: "Catfish/200/20/Fish -4/Catfish/An uncommon fish found in streams./Day^Spring Fall Winter")
Item.create!(item_key: 144, information: "Pike/100/15/Fish -4/Pike/A freshwater fish that's difficult to catch./Day Night^Summer Winter")
Item.create!(item_key: 145, information: "Sunfish/30/5/Fish -4/Sunfish/A common river fish./Day^Spring Summer")
Item.create!(item_key: 146, information: "Red Mullet/75/10/Fish -4/Red Mullet/Long ago these were kept as pets./Day^Summer Winter")
Item.create!(item_key: 147, information: "Herring/30/5/Fish -4/Herring/A common ocean fish./Day Night^Spring Winter")
Item.create!(item_key: 148, information: "Eel/85/12/Fish -4/Eel/A long, slippery little fish./Night^Spring Fall")
Item.create!(item_key: 149, information: "Octopus/150/-300/Fish -4/Octopus/A mysterious and intelligent creature./Day^Summer")
Item.create!(item_key: 150, information: "Red Snapper/50/10/Fish -4/Red Snapper/A popular fish with a nice red color./Day^Summer Fall Winter")
Item.create!(item_key: 151, information: "Squid/80/10/Fish -4/Squid/A deep sea creature that can grow to enormous size./Day^Winter")
Item.create!(item_key: 152, information: "Seaweed/20/5/Fish/Seaweed/It can be used in cooking./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 153, information: "Green Algae/15/5/Fish/Green Algae/It's really slimy./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 154, information: "Sea Cucumber/75/-10/Fish -4/Sea Cucumber/A slippery, slimy creature found on the ocean floor./Day^Fall Winter")
Item.create!(item_key: 155, information: "Super Cucumber/250/50/Fish -4/Super Cucumber/A rare, purple variety of sea cucumber./Night^Summer Fall")
Item.create!(item_key: 156, information: "Ghostfish/45/15/Fish -4/Ghostfish/A pale, blind fish found in underground lakes./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 157, information: "White Algae/25/8/Fish/White Algae/It's super slimy./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 158, information: "Stonefish/300/-300/Fish -4/Stonefish/A bizarre fish that's shaped like a brick./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 159, information: "Crimsonfish/1500/15/Fish -4/Crimsonfish/Lives deep in the ocean but likes to lay its eggs in the warm summer water./Day^Winter")
Item.create!(item_key: 160, information: "Angler/900/10/Fish -4/Angler/Uses a bioluminescent dangler to attract prey./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 161, information: "Ice Pip/500/15/Fish -4/Ice Pip/A rare fish that thrives in extremely cold conditions./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 162, information: "Lava Eel/700/20/Fish -4/Lava Eel/It can somehow survive in pools of red-hot lava./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 163, information: "Legend/5000/200/Fish -4/Legend/The king of all fish! They said he'd never be caught./Day^Winter")
Item.create!(item_key: 164, information: "Sandfish/75/5/Fish -4/Sandfish/It tries to hide using camouflage./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 165, information: "Scorpion Carp/150/-50/Fish -4/Scorpion Carp/It's like a regular carp but with a sharp stinger./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 166, information: "Treasure Chest/5000/-300/Basic/Treasure Chest/Wow, it's loaded with treasure! This is sure to fetch a good price./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 167, information: "Joja Cola/25/5/Fish -20/Joja Cola/The flagship product of Joja corporation./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 168, information: "Trash/0/-300/Fish -20/Trash/It's junk./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 169, information: "Driftwood/0/-300/Fish -20/Driftwood/A piece of wood from the sea./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 170, information: "Broken Glasses/0/-300/Fish -20/Broken Glasses/It looks like someone lost their glasses. They're busted./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 171, information: "Broken CD/0/-300/Fish -20/Broken CD/It's a JojaNet 2.0 trial CD. They must've made a billion of these things./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 172, information: "Soggy Newspaper/0/-300/Fish -20/Soggy Newspaper/This is trash./Day Night^Spring Summer Fall Winter")
Item.create!(item_key: 174, information: "Large Egg/95/15/Basic -5/Large Egg/It's an uncommonly large white egg!")
Item.create!(item_key: 176, information: "Egg/50/10/Basic -5/Egg/A regular white chicken egg.")
Item.create!(item_key: 178, information: "Hay/0/-300/Basic/Hay/Dried grass used as animal food.")
Item.create!(item_key: 180, information: "Egg/50/10/Basic -5/Egg/A regular brown chicken egg.")
Item.create!(item_key: 182, information: "Large Egg/95/15/Basic -5/Large Egg/It's an uncommonly large brown egg!")
Item.create!(item_key: 184, information: "Milk/125/15/Basic -6/Milk/A jug of cow's milk./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 186, information: "Large Milk/190/20/Basic -6/Large Milk/A large jug of cow's milk./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 188, information: "Green Bean/40/10/Basic -75/Green Bean/A juicy little bean with a cool, crisp snap.")
Item.create!(item_key: 190, information: "Cauliflower/175/30/Basic -75/Cauliflower/Valuable, but slow-growing. Despite its pale color, the florets are packed with nutrients.")
Item.create!(item_key: 192, information: "Potato/80/10/Basic -75/Potato/A widely cultivated tuber.")
Item.create!(item_key: 194, information: "Fried Egg/35/20/Cooking -7/Fried Egg/Sunny-side up./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 195, information: "Omelet/125/40/Cooking -7/Omelet/It's super fluffy./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 196, information: "Salad/110/45/Cooking -7/Salad/A healthy garden salad./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 197, information: "Cheese Cauliflower/300/55/Cooking -7/Cheese Cauliflower/It smells great!/food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 198, information: "Baked Fish/100/30/Cooking -7/Baked Fish/Baked fish on a bed of herbs./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 199, information: "Parsnip Soup/120/34/Cooking -7/Parsnip Soup/It's fresh and hearty./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 200, information: "Vegetable Medley/120/66/Cooking -7/Vegetable Medley/This is very nutritious./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 201, information: "Complete Breakfast/350/80/Cooking -7/Complete Breakfast/You'll feel ready to take on the world!/food/2 0 0 0 0 0 0 50 0 0 0/600")
Item.create!(item_key: 202, information: "Fried Calamari/150/32/Cooking -7/Fried Calamari/It's so chewy./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 203, information: "Strange Bun/225/40/Cooking -7/Strange Bun/What's inside?/food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 204, information: "Lucky Lunch/250/40/Cooking -7/Lucky Lunch/A special little meal./food/0 0 0 0 3 0 0 0 0 0 0/960")
Item.create!(item_key: 205, information: "Fried Mushroom/200/54/Cooking -7/Fried Mushroom/Earthy and aromatic./food/0 0 0 0 0 0 0 0 0 0 0 2/600")
Item.create!(item_key: 206, information: "Pizza/300/60/Cooking -7/Pizza/It's popular for all the right reasons./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 207, information: "Bean Hotpot/100/50/Cooking -7/Bean Hotpot/It sure is healthy./food/0 0 0 0 0 0 2 0 0 0 0/600")
Item.create!(item_key: 208, information: "Glazed Yams/200/80/Cooking -7/Glazed Yams/Sweet and satisfying... The sugar gives it a hint of caramel./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 209, information: "Carp Surprise/150/36/Cooking -7/Carp Surprise/It's bland and oily./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 210, information: "Hashbrowns/120/36/Cooking -7/Hashbrowns/Crispy and golden-brown!/food/1 0 0 0 0 0 0 0 0 0 0/480")
Item.create!(item_key: 211, information: "Pancakes/80/36/Cooking -7/Pancakes/A double stack of fluffy, soft pancakes./food/0 0 0 0 0 2 0 0 0 0 0/960")
Item.create!(item_key: 212, information: "Salmon Dinner/300/50/Cooking -7/Salmon Dinner/The lemon spritz makes it special./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 213, information: "Fish Taco/500/66/Cooking -7/Fish Taco/It smells delicious./food/0 2 0 0 0 0 0 0 0 0 0/600")
Item.create!(item_key: 214, information: "Crispy Bass/150/36/Cooking -7/Crispy Bass/Wow, the breading is perfect./food/0 0 0 0 0 0 0 0 64 0 0/600")
Item.create!(item_key: 215, information: "Pepper Poppers/200/52/Cooking -7/Pepper Poppers/Spicy breaded peppers filled with cheese./food/2 0 0 0 0 0 0 0 0 1 0/600")
Item.create!(item_key: 216, information: "Bread/60/20/Cooking -7/Bread/A crusty baguette./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 218, information: "Tom Kha Soup/250/70/Cooking -7/Tom Kha Soup/These flavors are incredible!/food/2 0 0 0 0 0 0 30 0 0 0/600")
Item.create!(item_key: 219, information: "Trout Soup/100/40/Cooking -7/Trout Soup/Pretty salty./food/0 1 0 0 0 0 0 0 0 0 0/400")
Item.create!(item_key: 220, information: "Chocolate Cake/200/60/Cooking -7/Chocolate Cake/Rich and moist with a thick fudge icing./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 221, information: "Pink Cake/480/100/Cooking -7/Pink Cake/There's little heart candies on top./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 222, information: "Rhubarb Pie/400/86/Cooking -7/Rhubarb Pie/Mmm, tangy and sweet!/food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 223, information: "Cookie/140/36/Cooking -7/Cookie/Very chewy./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 224, information: "Spaghetti/120/30/Cooking -7/Spaghetti/An old favorite./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 225, information: "Fried Eel/120/30/Cooking -7/Fried Eel/Greasy but flavorful./food/0 0 0 0 1 0 0 0 0 0 0/600")
Item.create!(item_key: 226, information: "Spicy Eel/175/46/Cooking -7/Spicy Eel/It's really spicy! Be careful./food/0 0 0 0 1 0 0 0 0 1 0/600")
Item.create!(item_key: 227, information: "Sashimi/75/30/Cooking -7/Sashimi/Raw fish sliced into thin pieces./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 228, information: "Maki Roll/220/40/Cooking -7/Maki Roll/Fish and rice wrapped in seaweed./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 229, information: "Tortilla/50/20/Cooking -7/Tortilla/Can be used as a vessel for food or eaten by itself./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 230, information: "Red Plate/400/96/Cooking -7/Red Plate/Full of antioxidants./food/0 0 0 0 0 0 0 50 0 0 0/300")
Item.create!(item_key: 231, information: "Eggplant Parmesan/200/70/Cooking -7/Eggplant Parmesan/Tangy, cheesy, and wonderful./food/0 0 1 0 0 0 0 0 0 0 3/400")
Item.create!(item_key: 232, information: "Rice Pudding/260/46/Cooking -7/Rice Pudding/It's creamy, sweet, and fun to eat./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 233, information: "Ice Cream/120/40/Cooking -7/Ice Cream/It's hard to find someone who doesn't like this./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 234, information: "Blueberry Tart/150/50/Cooking -7/Blueberry Tart/It's subtle and refreshing./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 235, information: "Autumn's Bounty/350/88/Cooking -7/Autumn's Bounty/A taste of the season./food/0 0 0 0 0 2 0 0 0 0 2/660")
Item.create!(item_key: 236, information: "Pumpkin Soup/300/80/Cooking -7/Pumpkin Soup/A seasonal favorite./food/0 0 0 0 2 0 0 0 0 0 2/660")
Item.create!(item_key: 237, information: "Super Meal/220/64/Cooking -7/Super Meal/It's a really energizing meal./food/0 0 0 0 0 0 0 40 0 1 0/300")
Item.create!(item_key: 238, information: "Cranberry Sauce/120/50/Cooking -7/Cranberry Sauce/A festive treat./food/0 0 2 0 0 0 0 0 0 0 0/300")
Item.create!(item_key: 239, information: "Stuffing/165/68/Cooking -7/Stuffing/Ahh... the smell of warm bread and sage./food/0 0 0 0 0 0 0 0 0 0 2/480")
Item.create!(item_key: 240, information: "Farmer's Lunch/150/80/Cooking -7/Farmer's Lunch/This'll keep you going./food/3 0 0 0 0 0 0 0 0 0 0/480")
Item.create!(item_key: 241, information: "Survival Burger/180/50/Cooking -7/Survival Burger/A convenient snack for the explorer./food/0 0 0 0 0 3 0 0 0 0 0/480")
Item.create!(item_key: 242, information: "Dish O' The Sea/220/60/Cooking -7/Dish O' The Sea/This'll keep you warm in the cold sea air./food/0 3 0 0 0 0 0 0 0 0 0/480")
Item.create!(item_key: 243, information: "Miner's Treat/200/50/Cooking -7/Miner's Treat/This should keep your energy up./food/0 0 3 0 0 0 0 0 32 0 0/480")
Item.create!(item_key: 244, information: "Roots Platter/100/50/Cooking -7/Roots Platter/This'll get you digging for more./food/0 0 0 0 0 0 0 0 0 0 0 3/480")
Item.create!(item_key: 245, information: "Sugar/50/10/Basic/Sugar/Adds sweetness to pastries and candies. Too much can be unhealthy.")
Item.create!(item_key: 246, information: "Wheat Flour/50/5/Basic/Wheat Flour/A common cooking ingredient made from crushed wheat seeds.")
Item.create!(item_key: 247, information: "Oil/100/5/Basic/Oil/All purpose cooking oil./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 248, information: "Garlic/60/8/Basic -75/Garlic/Adds a wonderful zestiness to dishes. High quality garlic can be pretty spicy.")
Item.create!(item_key: 250, information: "Kale/110/20/Basic -75/Kale/The waxy leaves are great in soups and stir frys.")
Item.create!(item_key: 252, information: "Rhubarb/220/-300/Basic -79/Rhubarb/The stalks are extremely tart, but make a great dessert when sweetened.")
Item.create!(item_key: 254, information: "Melon/250/45/Basic -79/Melon/A cool, sweet summer treat.")
Item.create!(item_key: 256, information: "Tomato/60/8/Basic -75/Tomato/Rich and slightly tangy, the Tomato has a wide variety of culinary uses.")
Item.create!(item_key: 257, information: "Morel/150/8/Basic -81/Morel/Sought after for its unique nutty flavor.")
Item.create!(item_key: 258, information: "Blueberry/50/10/Basic -79/Blueberry/A popular berry reported to have many health benefits. The blue skin has the highest nutrient concentration.")
Item.create!(item_key: 259, information: "Fiddlehead Fern/90/10/Basic -75/Fiddlehead Fern/The young shoots are an edible specialty.")
Item.create!(item_key: 260, information: "Hot Pepper/40/5/Basic -79/Hot Pepper/Fiery hot with a hint of sweetness.")
Item.create!(item_key: 262, information: "Wheat/25/-300/Basic -75/Wheat/One of the most widely cultivated grains. Makes a great flour for breads and cakes.")
Item.create!(item_key: 264, information: "Radish/90/18/Basic -75/Radish/A crisp and refreshing root vegetable with hints of pepper when eaten raw.")
Item.create!(item_key: 266, information: "Red Cabbage/260/30/Basic -75/Red Cabbage/Often used in salads and coleslaws. The color can range from purple to blue to green-yellow depending on soil conditions.")
Item.create!(item_key: 268, information: "Starfruit/750/50/Basic -79/Starfruit/An extremely juicy fruit that grows in hot, humid weather. Slightly sweet with a sour undertone.")
Item.create!(item_key: 270, information: "Corn/50/10/Basic -75/Corn/One of the most popular grains. The sweet, fresh cobs are a summer favorite.")
Item.create!(item_key: 272, information: "Eggplant/60/8/Basic -75/Eggplant/A rich and wholesome relative of the tomato. Delicious fried or stewed.")
Item.create!(item_key: 274, information: "Artichoke/160/12/Basic -75/Artichoke/The bud of a thistle plant. The spiny outer leaves conceal a fleshy, filling interior.")
Item.create!(item_key: 276, information: "Pumpkin/320/-300/Basic -75/Pumpkin/A fall favorite, grown for its crunchy seeds and delicately flavored flesh. As a bonus, the hollow shell can be carved into a festive decoration.")
Item.create!(item_key: 278, information: "Bok Choy/80/10/Basic -75/Bok Choy/The leafy greens and fibrous stalks are healthy and delicious.")
Item.create!(item_key: 280, information: "Yam/160/18/Basic -75/Yam/A starchy tuber with a lot of culinary versatility.")
Item.create!(item_key: 281, information: "Chanterelle/160/30/Basic -81/Chanterelle/A tasty mushroom with a fruity smell and slightly peppery flavor.")
Item.create!(item_key: 282, information: "Cranberries/75/15/Basic -79/Cranberries/These tart red berries are a traditional winter food.")
Item.create!(item_key: 283, information: "Holly/80/-15/Basic -81/Holly/The leaves and bright red berries make a popular winter decoration.")
Item.create!(item_key: 284, information: "Beet/100/12/Basic -75/Beet/A sweet and earthy root vegatable. As a bonus, the leaves make a great salad.")
Item.create!(item_key: 286, information: "Cherry Bomb/50/-300/Crafting -8/Cherry Bomb/Generates a small explosion. Stand back!")
Item.create!(item_key: 287, information: "Bomb/50/-300/Crafting -8/Bomb/Generates an explosion. Watch out!")
Item.create!(item_key: 288, information: "Mega Bomb/50/-300/Crafting -8/Mega Bomb/Generates a powerful explosion. Use with extreme caution.")
Item.create!(item_key: 290, information: "Stone/50/-300/Basic/Stone/...")
Item.create!(item_key: 294, information: "Twig/1/-300/Crafting/Twig/...")
Item.create!(item_key: 295, information: "Twig/1/-300/Crafting/Twig/...")
Item.create!(item_key: 296, information: "Salmonberry/5/10/Basic -79/Salmonberry/A spring-time berry with the flavor of the forest.")
Item.create!(item_key: 297, information: "Grass Starter/50/-300/Crafting/Grass Starter/Place this on your farm to start a new patch of grass.")
Item.create!(item_key: 298, information: "Hardwood Fence/10/-300/Crafting -8/Hardwood Fence/The most durable type of fence.")
Item.create!(item_key: 299, information: "Amaranth Seeds/35/-300/Seeds -74/Amaranth Seeds/Plant these in the fall. Takes 7 days to grow. Harvest with the scythe.")
Item.create!(item_key: 300, information: "Amaranth/150/20/Basic -75/Amaranth/A purple grain cultivated by an ancient civilization.")
Item.create!(item_key: 301, information: "Grape Starter/30/-300/Seeds -74/Grape Starter/Plant these in the fall. Takes 10 days to grow, but keeps producing after that. Grows on a trellis.")
Item.create!(item_key: 302, information: "Hops Starter/30/-300/Seeds -74/Hops Starter/Plant these in the summer. Takes 11 days to grow, but keeps producing after that. Grows on a trellis.")
Item.create!(item_key: 303, information: "Pale Ale/300/20/Basic -26/Pale Ale/Drink in moderation./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 304, information: "Hops/25/18/Basic -75/Hops/A bitter, tangy flower used to flavor beer.")
Item.create!(item_key: 305, information: "Void Egg/65/15/Basic -5/Void Egg/A jet-black egg with red flecks. It's warm to the touch.")
Item.create!(item_key: 306, information: "Mayonnaise/190/-300/Basic -26/Mayonnaise/It looks spreadable.")
Item.create!(item_key: 307, information: "Duck Mayonnaise/375/-300/Basic -26/Duck Mayonnaise/It's a rich, yellow mayonnaise.")
Item.create!(item_key: 308, information: "Void Mayonnaise/275/-30/Basic -26/Void Mayonnaise/A thick, black paste that smells like burnt hair.")
Item.create!(item_key: 309, information: "Acorn/20/-300/Crafting -74/Acorn/Place this on your farm to plant an oak tree.")
Item.create!(item_key: 310, information: "Maple Seed/5/-300/Crafting -74/Maple Seed/Place this on your farm to plant a maple tree.")
Item.create!(item_key: 311, information: "Pine Cone/5/-300/Crafting -74/Pine Cone/Place this on your farm to plant a pine tree.")
Item.create!(item_key: 313, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 314, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 315, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 316, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 317, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 318, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 319, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 320, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 321, information: "Weeds/50/-300/Crafting/Weeds/...")
Item.create!(item_key: 322, information: "Wood Fence/1/-300/Crafting -8/Wood Fence/Keeps grass and animals contained!")
Item.create!(item_key: 323, information: "Stone Fence/2/-300/Crafting -8/Stone Fence/Lasts longer than a wood fence.")
Item.create!(item_key: 324, information: "Iron Fence/6/-300/Crafting -8/Iron Fence/Lasts longer than a stone fence.")
Item.create!(item_key: 325, information: "Gate/4/-300/Crafting -8/Gate/Allows you to pass through a fence.")
Item.create!(item_key: 326, information: "Dwarvish Translation Guide/50/-300/Crafting -8/Dwarvish Translation Guide/Teaches you dwarvish.")
Item.create!(item_key: 328, information: "Wood Floor/1/-300/Crafting -24/Wood Floor/Place on the ground to create paths or to decorate your floors.")
Item.create!(item_key: 329, information: "Stone Floor/1/-300/Crafting -24/Stone Floor/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 330, information: "Clay/20/-300/Basic -16/Clay/Used in crafting and construction.")
Item.create!(item_key: 331, information: "Weathered Floor/1/-300/Crafting -24/Weathered Floor/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 333, information: "Crystal Floor/1/-300/Crafting -24/Crystal Floor/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 334, information: "Copper Bar/60/-300/Basic -15/Copper Bar/A bar of pure copper.")
Item.create!(item_key: 335, information: "Iron Bar/120/-300/Basic -15/Iron Bar/A bar of pure iron.")
Item.create!(item_key: 336, information: "Gold Bar/250/-300/Basic -15/Gold Bar/A bar of pure gold.")
Item.create!(item_key: 337, information: "Iridium Bar/1000/-300/Basic -15/Iridium Bar/A bar of pure iridium.")
Item.create!(item_key: 338, information: "Refined Quartz/50/-300/Basic -15/Refined Quartz/A more pure form of quartz.")
Item.create!(item_key: 340, information: "Honey/100/-300/Basic -26/Honey/It's a sweet syrup produced by bees.")
Item.create!(item_key: 341, information: "Tea Set/200/-300/Basic -24/Tea Set/Fine porcelain.")
Item.create!(item_key: 342, information: "Pickles/100/-300/Basic -26/Pickles/A jar of your home-made pickles.")
Item.create!(item_key: 343, information: "Stone/100/-300/Basic/Stone/Stone.")
Item.create!(item_key: 344, information: "Jelly/160/-300/Basic -26/Jelly/Gooey.")
Item.create!(item_key: 346, information: "Beer/200/20/Basic -26/Beer/Drink in moderation./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 347, information: "Rare Seed/200/-300/Seeds -74/Rare Seed/Sow in fall. Takes all season to grow.")
Item.create!(item_key: 348, information: "Wine/400/20/Basic -26/Wine/Drink in moderation./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 349, information: "Energy Tonic/500/200/Crafting/Energy Tonic/Restores a lot of energy./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 350, information: "Juice/150/30/Basic -26/Juice/A sweet, nutritious beverage./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 351, information: "Muscle Remedy/500/20/Crafting/Muscle Remedy/When you've pushed your body too hard, drink this to remove 'Exhaustion'./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 368, information: "Basic Fertilizer/2/-300/Basic -19/Basic Fertilizer/Improves soil quality a little, increasing your chance to grow quality crops. Mix into tilled soil.")
Item.create!(item_key: 369, information: "Quality Fertilizer/10/-300/Basic -19/Quality Fertilizer/Improves soil quality, increasing your chance to grow quality crops. Mix into tilled soil.")
Item.create!(item_key: 370, information: "Basic Retaining Soil/4/-300/Basic -19/Basic Retaining Soil/This soil has a chance of staying watered overnight. Mix into tilled soil.")
Item.create!(item_key: 371, information: "Quality Retaining Soil/5/-300/Basic -19/Quality Retaining Soil/This soil has a good chance of staying watered overnight. Mix into tilled soil.")
Item.create!(item_key: 372, information: "Clam/50/-300/Basic -23/Clam/Someone lived here once.")
Item.create!(item_key: 373, information: "Golden Pumpkin/2500/-300/Basic/Golden Pumpkin/It's valuable but has no other purpose.")
Item.create!(item_key: 376, information: "Poppy/140/18/Basic -80/Poppy/In addition to its colorful flower, the Poppy has culinary and medicinal uses.")
Item.create!(item_key: 378, information: "Copper Ore/5/-300/Basic -15/Copper Ore/A common ore that can be smelted into bars.")
Item.create!(item_key: 380, information: "Iron Ore/10/-300/Basic -15/Iron Ore/A fairly common ore that can be smelted into bars.")
Item.create!(item_key: 382, information: "Coal/15/-300/Basic -15/Coal/A combustible rock that is useful for crafting and smelting.")
Item.create!(item_key: 384, information: "Gold Ore/25/-300/Basic -15/Gold Ore/A precious ore that can be smelted into bars.")
Item.create!(item_key: 386, information: "Iridium Ore/100/-300/Basic -15/Iridium Ore/An exotic ore with many curious properties. Can be smelted into bars.")
Item.create!(item_key: 388, information: "Wood/2/-300/Basic -16/Wood/A sturdy, yet flexible plant material with a wide variety of uses.")
Item.create!(item_key: 390, information: "Stone/2/-300/Basic -16/Stone/A common material with many uses in crafting and building.")
Item.create!(item_key: 392, information: "Nautilus Shell/120/-300/Basic -23/Nautilus Shell/An ancient shell.")
Item.create!(item_key: 393, information: "Coral/80/-300/Basic -23/Coral/A colony of tiny creatures that clump together to form beautiful structures.")
Item.create!(item_key: 394, information: "Rainbow Shell/300/-300/Basic -23/Rainbow Shell/It's a very beautiful shell.")
Item.create!(item_key: 395, information: "Coffee/150/1/Crafting/Coffee/It smells delicious. This is sure to give you a boost./drink/0 0 0 0 0 0 0 0 0 1 0/120")
Item.create!(item_key: 396, information: "Spice Berry/80/10/Basic -79/Spice Berry/It fills the air with a pungent aroma.")
Item.create!(item_key: 397, information: "Sea Urchin/160/-300/Basic -23/Sea Urchin/A slow-moving, spiny creature that some consider a delicacy.")
Item.create!(item_key: 398, information: "Grape/80/15/Basic -79/Grape/A sweet cluster of fruit.")
Item.create!(item_key: 399, information: "Spring Onion/8/5/Basic -81/Spring Onion/These grow wild during the spring.")
Item.create!(item_key: 400, information: "Strawberry/120/20/Basic -79/Strawberry/A sweet, juicy favorite with an appealing red color.")
Item.create!(item_key: 401, information: "Straw Floor/1/-300/Crafting -24/Straw Floor/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 402, information: "Sweet Pea/50/0/Basic -80/Sweet Pea/A fragrant summer flower.")
Item.create!(item_key: 403, information: "Field Snack/20/18/Crafting/Field Snack/A quick snack to fuel the hungry forager.")
Item.create!(item_key: 404, information: "Common Mushroom/40/15/Basic -81/Common Mushroom/Slightly nutty, with good texture.")
Item.create!(item_key: 405, information: "Wood Path/1/-300/Crafting -24/Wood Path/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 406, information: "Wild Plum/80/10/Basic -79/Wild Plum/Tart and juicy with a pungent aroma.")
Item.create!(item_key: 407, information: "Gravel Path/1/-300/Crafting -24/Gravel Path/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 408, information: "Hazelnut/90/12/Basic -81/Hazelnut/That's one big hazelnut!")
Item.create!(item_key: 409, information: "Crystal Path/1/-300/Crafting -24/Crystal Path/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 410, information: "Blackberry/20/10/Basic -79/Blackberry/An early-fall treat.")
Item.create!(item_key: 411, information: "Cobblestone Path/1/-300/Crafting -24/Cobblestone Path/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 412, information: "Winter Root/70/10/Basic -81/Winter Root/A starchy tuber.")
Item.create!(item_key: 413, information: "Blue Slime Egg/1750/-300/Basic/Blue Slime Egg/Can be hatched in a slime incubator.")
Item.create!(item_key: 414, information: "Crystal Fruit/150/25/Basic -79/Crystal Fruit/A delicate fruit that pops up from the snow.")
Item.create!(item_key: 415, information: "Stepping Stone Path/1/-300/Crafting -24/Stepping Stone Path/Place on the ground to create paths or to spruce up your floors.")
Item.create!(item_key: 416, information: "Snow Yam/100/12/Basic -81/Snow Yam/This little yam was hiding beneath the snow.")
Item.create!(item_key: 417, information: "Sweet Gem Berry/3000/-300/Basic -17/Sweet Gem Berry/It's by far the sweetest thing you've ever smelled.")
Item.create!(item_key: 418, information: "Crocus/60/0/Basic -80/Crocus/A flower that can bloom in the winter.")
Item.create!(item_key: 419, information: "Vinegar/100/5/Basic/Vinegar/An aged fermented liquid used in many cooking recipes./drink")
Item.create!(item_key: 420, information: "Red Mushroom/75/-20/Basic -81/Red Mushroom/A spotted mushroom sometimes found in caves.")
Item.create!(item_key: 421, information: "Sunflower/80/18/Basic -80/Sunflower/A common misconception is that the flower turns so it's always facing the sun.")
Item.create!(item_key: 422, information: "Purple Mushroom/250/50/Basic -81/Purple Mushroom/A rare mushroom found deep in caves.")
Item.create!(item_key: 423, information: "Rice/100/5/Basic/Rice/A basic grain often served under vegetables.")
Item.create!(item_key: 424, information: "Cheese/200/50/Basic -26/Cheese/It's your basic cheese.")
Item.create!(item_key: 425, information: "Fairy Seeds/100/-300/Seeds -74/Fairy Seeds/Plant in fall. Takes 12 days to produce a mysterious flower. Assorted Colors.")
Item.create!(item_key: 426, information: "Goat Cheese/375/50/Basic -26/Goat Cheese/Soft cheese made from goat's milk.")
Item.create!(item_key: 427, information: "Tulip Bulb/10/-300/Seeds -74/Tulip Bulb/Plant in spring. Takes 6 days to produce a colorful flower. Assorted colors.")
Item.create!(item_key: 428, information: "Cloth/470/-300/Basic -26/Cloth/A bolt of fine wool cloth.")
Item.create!(item_key: 429, information: "Jazz Seeds/15/-300/Seeds -74/Jazz Seeds/Plant in spring. Takes 7 days to produce a blue puffball flower.")
Item.create!(item_key: 430, information: "Truffle/625/5/Basic -17/Truffle/A gourmet type of mushroom with a unique taste.")
Item.create!(item_key: 431, information: "Sunflower Seeds/20/-300/Seeds -74/Sunflower Seeds/Plant in summer or fall. Takes 8 days to produce a large sunflower. Yields more seeds at harvest.")
Item.create!(item_key: 432, information: "Truffle Oil/1065/15/Basic -26/Truffle Oil/A gourmet cooking ingredient./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 433, information: "Coffee Bean/15/-300/Seeds -74/Coffee Bean/Plant in spring or summer to grow a coffee plant. Place five beans in a keg to make coffee.")
Item.create!(item_key: 434, information: "Stardrop/7777/100/Crafting/Stardrop/A mysterious fruit that empowers those who eat it. The flavor is like a dream... a powerful personal experience, yet difficult to describe to others.")
Item.create!(item_key: 436, information: "Goat Milk/225/25/Basic -6/Goat Milk/The milk of a goat./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 437, information: "Red Slime Egg/2500/-300/Basic/Red Slime Egg/Can be hatched in a slime incubator.")
Item.create!(item_key: 438, information: "L. Goat Milk/345/35/Basic -6/L. Goat Milk/A gallon of creamy goat's milk./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 439, information: "Purple Slime Egg/5000/-300/Basic/Purple Slime Egg/Can be hatched in a slime incubator.")
Item.create!(item_key: 440, information: "Wool/340/-300/Basic -18/Wool/Soft, fluffy wool.")
Item.create!(item_key: 441, information: "Explosive Ammo/20/-300/Basic/Explosive Ammo/Fire this with the slingshot.")
Item.create!(item_key: 442, information: "Duck Egg/95/15/Basic -5/Duck Egg/It's still warm.")
Item.create!(item_key: 444, information: "Duck Feather/125/-300/Basic -18/Duck Feather/It's so colorful.")
Item.create!(item_key: 446, information: "Rabbit's Foot/565/-300/Basic -18/Rabbit's Foot/Some say it's lucky.")
Item.create!(item_key: 449, information: "Stone Base/0/-300/asdf/Stone Base/A simple block of stone.")
Item.create!(item_key: 450, information: "Stone/0/-300/asdf/Stone/Stone.")
Item.create!(item_key: 452, information: "Weeds/0/-300/asdf/Weeds/A cluster of dry old bushes.")
Item.create!(item_key: 453, information: "Poppy Seeds/50/-300/Seeds -74/Poppy Seeds/Plant in summer. Produces a bright red flower in 7 days.")
Item.create!(item_key: 454, information: "Ancient Fruit/550/-300/Basic -79/Ancient Fruit/It's been dormant for eons.")
Item.create!(item_key: 455, information: "Spangle Seeds/25/-300/Seeds -74/Spangle Seeds/Plant in summer. Takes 8 days to produce a vibrant tropical flower. Assorted colors.")
Item.create!(item_key: 456, information: "Algae Soup/100/30/Cooking -7/Algae Soup/It's a little slimy./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 457, information: "Pale Broth/150/50/Cooking -7/Pale Broth/A delicate broth with a hint of sulfur./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 458, information: "Bouquet/100/-300/Basic/Bouquet/A gift that shows your romantic interest.")
Item.create!(item_key: 459, information: "Mead/200/30/Basic -26/Mead/A fermented beverage made from honey. Drink in moderation./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 460, information: "Mermaid's Pendant/2500/-300/Basic/Mermaid's Pendant/Give this to the person you want to marry.")
Item.create!(item_key: 461, information: "Decorative Pot/200/-300/Crafting/Decorative Pot/A replica of an ancient pot.")
Item.create!(item_key: 463, information: "Drum Block/100/-300/Crafting/Drum Block/Plays a drum sound when you walk past.")
Item.create!(item_key: 464, information: "Flute Block/100/-300/Crafting/Flute Block/Plays a flute sound when you walk past.")
Item.create!(item_key: 465, information: "Speed-Gro/20/-300/Basic -19/Speed-Gro/Stimulates leaf production. Guaranteed to increase growth rate by at least 10%. Mix into tilled soil.")
Item.create!(item_key: 466, information: "Deluxe Speed-Gro/40/-300/Basic -19/Deluxe Speed-Gro/Stimulates leaf production. Guaranteed to increase growth rate by at least 25%. Mix into tilled soil.")
Item.create!(item_key: 472, information: "Parsnip Seeds/10/-300/Seeds -74/Parsnip Seeds/Plant these in the spring. Takes 4 days to mature.")
Item.create!(item_key: 473, information: "Bean Starter/30/-300/Seeds -74/Bean Starter/Plant these in the spring. Takes 10 days to mature, but keeps producing after that. Yields multiple beans per harvest. Grows on a trellis.")
Item.create!(item_key: 474, information: "Cauliflower Seeds/40/-300/Seeds -74/Cauliflower Seeds/Plant these in the spring. Takes 12 days to produce a large cauliflower.")
Item.create!(item_key: 475, information: "Potato Seeds/25/-300/Seeds -74/Potato Seeds/Plant these in the spring. Takes 6 days to mature, and has a chance of yielding multiple potatoes at harvest.")
Item.create!(item_key: 476, information: "Garlic Seeds/20/-300/Seeds -74/Garlic Seeds/Plant these in the spring. Takes 4 days to mature.")
Item.create!(item_key: 477, information: "Kale Seeds/35/-300/Seeds -74/Kale Seeds/Plant these in the spring. Takes 6 days to mature. Harvest with the scythe.")
Item.create!(item_key: 478, information: "Rhubarb Seeds/50/-300/Seeds -74/Rhubarb Seeds/Plant these in the spring. Takes 13 days to mature.")
Item.create!(item_key: 479, information: "Melon Seeds/40/-300/Seeds -74/Melon Seeds/Plant these in the summer. Takes 12 days to mature.")
Item.create!(item_key: 480, information: "Tomato Seeds/25/-300/Seeds -74/Tomato Seeds/Plant these in the summer. Takes 11 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 481, information: "Blueberry Seeds/40/-300/Seeds -74/Blueberry Seeds/Plant these in the summer. Takes 13 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 482, information: "Pepper Seeds/20/-300/Seeds -74/Pepper Seeds/Plant these in the summer. Takes 5 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 483, information: "Wheat Seeds/5/-300/Seeds -74/Wheat Seeds/Plant these in the summer or fall. Takes 4 days to mature. Harvest with the scythe.")
Item.create!(item_key: 484, information: "Radish Seeds/20/-300/Seeds -74/Radish Seeds/Plant these in the summer. Takes 6 days to mature.")
Item.create!(item_key: 485, information: "Red Cabbage Seeds/50/-300/Seeds -74/Red Cabbage Seeds/Plant these in the summer. Takes 9 days to mature.")
Item.create!(item_key: 486, information: "Starfruit Seeds/200/-300/Seeds -74/Starfruit Seeds/Plant these in the summer. Takes 13 days to mature.")
Item.create!(item_key: 487, information: "Corn Seeds/75/-300/Seeds -74/Corn Seeds/Plant these in the summer or fall. Takes 14 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 488, information: "Eggplant Seeds/10/-300/Seeds -74/Eggplant Seeds/Plant these in the fall. Takes 5 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 489, information: "Artichoke Seeds/15/-300/Seeds -74/Artichoke Seeds/Plant these in the fall. Takes 8 days to mature.")
Item.create!(item_key: 490, information: "Pumpkin Seeds/50/-300/Seeds -74/Pumpkin Seeds/Plant these in the fall. Takes 13 days to mature.")
Item.create!(item_key: 491, information: "Bok Choy Seeds/25/-300/Seeds -74/Bok Choy Seeds/Plant these in the fall. Takes 4 days to mature.")
Item.create!(item_key: 492, information: "Yam Seeds/30/-300/Seeds -74/Yam Seeds/Plant these in the fall. Takes 10 days to mature.")
Item.create!(item_key: 493, information: "Cranberry Seeds/120/-300/Seeds -74/Cranberry Seeds/Plant these in the fall. Takes 7 days to mature, and continues to produce after first harvest.")
Item.create!(item_key: 494, information: "Beet Seeds/10/-300/Seeds -74/Beet Seeds/Plant these in the fall. Takes 6 days to mature.")
Item.create!(item_key: 495, information: "Spring Seeds/35/-300/Seeds -74/Spring Seeds/An assortment of wild spring seeds.")
Item.create!(item_key: 496, information: "Summer Seeds/55/-300/Seeds -74/Summer Seeds/An assortment of wild summer seeds.")
Item.create!(item_key: 497, information: "Fall Seeds/45/-300/Seeds -74/Fall Seeds/An assortment of wild fall seeds.")
Item.create!(item_key: 498, information: "Winter Seeds/30/-300/Seeds -74/Winter Seeds/An assortment of wild winter seeds.")
Item.create!(item_key: 499, information: "Ancient Seeds/30/-300/Seeds -74/Ancient Seeds/Could these still grow?")
Item.create!(item_key: 516, information: "Small Glow Ring/100/-300/Ring/Small Glow Ring/Emits a small, constant light.")
Item.create!(item_key: 517, information: "Glow Ring/200/-300/Ring/Glow Ring/Emits a constant light.")
Item.create!(item_key: 518, information: "Small Magnet Ring/100/-300/Ring/Small Magnet Ring/Slightly increases your radius for collecting items.")
Item.create!(item_key: 519, information: "Magnet Ring/200/-300/Ring/Magnet Ring/Increases your radius for collecting items.")
Item.create!(item_key: 520, information: "Slime Charmer Ring/700/-300/Ring/Slime Charmer Ring/Prevents damage from slimes.")
Item.create!(item_key: 521, information: "Warrior Ring/1500/-300/Ring/Warrior Ring/Occasionally infuses the wearer with \"warrior energy\" after slaying a monster.")
Item.create!(item_key: 522, information: "Vampire Ring/1500/-300/Ring/Vampire Ring/Gain a little health every time you slay a monster.")
Item.create!(item_key: 523, information: "Savage Ring/1500/-300/Ring/Savage Ring/Gain a short speed boost whenever you slay a monster.")
Item.create!(item_key: 524, information: "Ring of Yoba/1500/-300/Ring/Ring of Yoba/Occasionally shields the wearer from damage.")
Item.create!(item_key: 525, information: "Sturdy Ring/1500/-300/Ring/Sturdy Ring/Cuts the duration of negative status effects in half.")
Item.create!(item_key: 526, information: "Burglar's Ring/1500/-300/Ring/Burglar's Ring/Monsters have a greater chance of dropping loot.")
Item.create!(item_key: 527, information: "Iridium Band/2000/-300/Ring/Iridium Band/Glows, attracts items, and increases attack damage by 10%.")
Item.create!(item_key: 528, information: "Jukebox Ring/200/-300/Ring/Jukebox Ring/Plays a random assortment of music you've heard.")
Item.create!(item_key: 529, information: "Amethyst Ring/200/-300/Ring/Amethyst Ring/Increases knockback by 10%.")
Item.create!(item_key: 530, information: "Topaz Ring/200/-300/Ring/Topaz Ring/Increases weapon precision by 10%.")
Item.create!(item_key: 531, information: "Aquamarine Ring/400/-300/Ring/Aquamarine Ring/Increases critical strike chance by 10%.")
Item.create!(item_key: 532, information: "Jade Ring/400/-300/Ring/Jade Ring/Increases critical strike power by 10%.")
Item.create!(item_key: 533, information: "Emerald Ring/600/-300/Ring/Emerald Ring/Increases weapon speed by 10%.")
Item.create!(item_key: 534, information: "Ruby Ring/600/-300/Ring/Ruby Ring/Increases attack by 10%.")
Item.create!(item_key: 535, information: "Geode/50/-300/Basic/Geode/A blacksmith can break this open for you./538 542 548 549 552 555 556 557 558 566 568 569 571 574 576 121")
Item.create!(item_key: 536, information: "Frozen Geode/100/-300/Basic/Frozen Geode/A blacksmith can break this open for you./541 544 545 546 550 551 559 560 561 564 567 572 573 577 123")
Item.create!(item_key: 537, information: "Magma Geode/150/-300/Basic/Magma Geode/A blacksmith can break this open for you./539 540 543 547 553 554 562 563 565 570 575 578 122")
Item.create!(item_key: 538, information: "Alamite/150/-300/Minerals -12/Alamite/Its distinctive fluorescence makes it a favorite among rock collectors.")
Item.create!(item_key: 539, information: "Bixite/300/-300/Minerals -12/Bixite/A dark metallic Mineral sought after for its cubic structure.")
Item.create!(item_key: 540, information: "Baryte/50/-300/Minerals -12/Baryte/The best specimens resemble a desert rose.")
Item.create!(item_key: 541, information: "Aerinite/125/-300/Minerals -12/Aerinite/These crystals are curiously light.")
Item.create!(item_key: 542, information: "Calcite/75/-300/Minerals -12/Calcite/This yellow crystal is speckled with shimmering nodules.")
Item.create!(item_key: 543, information: "Dolomite/300/-300/Minerals -12/Dolomite/It can occur in coral reefs, often near an underwater volcano.")
Item.create!(item_key: 544, information: "Esperite/100/-300/Minerals -12/Esperite/The crystals glow bright green when stimulated.")
Item.create!(item_key: 545, information: "Fluorapatite/200/-300/Minerals -12/Fluorapatite/Small amounts are found in human teeth.")
Item.create!(item_key: 546, information: "Geminite/150/-300/Minerals -12/Geminite/Occurs in brilliant clusters.")
Item.create!(item_key: 547, information: "Helvite/450/-300/Minerals -12/Helvite/It grows in a triangular column.")
Item.create!(item_key: 548, information: "Jamborite/150/-300/Minerals -12/Jamborite/The crystals are so tightly packed it almost looks fuzzy.")
Item.create!(item_key: 549, information: "Jagoite/115/-300/Minerals -12/Jagoite/A high volume of tiny crystals makes it very glittery.")
Item.create!(item_key: 550, information: "Kyanite/250/-300/Minerals -12/Kyanite/The geometric faces are as smooth as glass.")
Item.create!(item_key: 551, information: "Lunarite/200/-300/Minerals -12/Lunarite/The cratered white orbs form a tight cluster.")
Item.create!(item_key: 552, information: "Malachite/100/-300/Minerals -12/Malachite/A popular ornamental stone, used in sculpture and to make green paint.")
Item.create!(item_key: 553, information: "Neptunite/400/-300/Minerals -12/Neptunite/A jet-black crystal that is unusually reflective.")
Item.create!(item_key: 554, information: "Lemon Stone/200/-300/Minerals -12/Lemon Stone/Some claim the powdered crystal is a dwarvish delicacy.")
Item.create!(item_key: 555, information: "Nekoite/80/-300/Minerals -12/Nekoite/The delicate shards form a tiny pink meadow.")
Item.create!(item_key: 556, information: "Orpiment/80/-300/Minerals -12/Orpiment/Despite its high toxicity, this Mineral is widely used in manufacturing and folk medicine.")
Item.create!(item_key: 557, information: "Petrified Slime/120/-300/Minerals -12/Petrified Slime/This little guy may be 100,000 years old.")
Item.create!(item_key: 558, information: "Thunder Egg/100/-300/Minerals -12/Thunder Egg/According to legend, angry thunder spirits would throw these stones at one another.")
Item.create!(item_key: 559, information: "Pyrite/120/-300/Minerals -12/Pyrite/Commonly known as \"Fool's Gold\".")
Item.create!(item_key: 560, information: "Ocean Stone/220/-300/Minerals -12/Ocean Stone/An old legend claims these stones are the mosaics of ancient mermaids.")
Item.create!(item_key: 561, information: "Ghost Crystal/200/-300/Minerals -12/Ghost Crystal/There is an aura of coldness around this crystal.")
Item.create!(item_key: 562, information: "Tigerseye/275/-300/Minerals -12/Tigerseye/A stripe of shimmering gold gives this gem a warm luster.")
Item.create!(item_key: 563, information: "Jasper/150/-300/Minerals -12/Jasper/When polished, this stone becomes attactively luminous. Prized by ancient peoples for thousands of years.")
Item.create!(item_key: 564, information: "Opal/150/-300/Minerals -12/Opal/Its internal structure causes it to reflect a rainbow of light.")
Item.create!(item_key: 565, information: "Fire Opal/350/-300/Minerals -12/Fire Opal/A rare variety of opal, named for its red spots.")
Item.create!(item_key: 566, information: "Celestine/125/-300/Minerals -12/Celestine/Some early life forms had bones made from this.")
Item.create!(item_key: 567, information: "Marble/110/-300/Minerals -12/Marble/A very popular material for sculptures and construction.")
Item.create!(item_key: 568, information: "Sandstone/60/-300/Minerals -12/Sandstone/A common type of stone with red and brown striations.")
Item.create!(item_key: 569, information: "Granite/75/-300/Minerals -12/Granite/A speckled Mineral that is commonly used in construction.")
Item.create!(item_key: 570, information: "Basalt/175/-300/Minerals -12/Basalt/Forms near searing hot magma.")
Item.create!(item_key: 571, information: "Limestone/15/-300/Minerals -12/Limestone/A very common type of stone. It's not worth very much.")
Item.create!(item_key: 572, information: "Soapstone/120/-300/Minerals -12/Soapstone/Because of its relatively soft consistency, this stone is very popular for carving.")
Item.create!(item_key: 573, information: "Hematite/150/-300/Minerals -12/Hematite/An iron-based Mineral with interesting magnetic properties.")
Item.create!(item_key: 574, information: "Mudstone/25/-300/Minerals -12/Mudstone/A fine-grained rock made from ancient clay or mud.")
Item.create!(item_key: 575, information: "Obsidian/200/-300/Minerals -12/Obsidian/A volcanic glass that forms when lava cools rapidly.")
Item.create!(item_key: 576, information: "Slate/85/-300/Minerals -12/Slate/It's extremely resistant to water, making it a good roofing material.")
Item.create!(item_key: 577, information: "Fairy Stone/250/-300/Minerals -12/Fairy Stone/An old miner's song suggests these are made from the bones of ancient fairies.")
Item.create!(item_key: 578, information: "Star Shards/500/-300/Minerals -12/Star Shards/No one knows how these form. Some scientists claim that the microscopic structure displays unnatural regularity.")
Item.create!(item_key: 579, information: "Prehistoric Scapula/100/-300/Arch/Prehistoric Scapula/Commonly known as a \"shoulder blade\"... It's unclear what species it belonged to./Item 1 289/Town .01")
Item.create!(item_key: 580, information: "Prehistoric Tibia/100/-300/Arch/Prehistoric Tibia/A thick and sturdy leg bone./Item 1 289/Forest .01")
Item.create!(item_key: 581, information: "Prehistoric Skull/100/-300/Arch/Prehistoric Skull/This is definitely a mammalian skull./Item 1 289/Mountain .01")
Item.create!(item_key: 582, information: "Skeletal Hand/100/-300/Arch/Skeletal Hand/It's a wonder all these ancient little pieces lasted so long./Item 1 289/Beach .01")
Item.create!(item_key: 583, information: "Prehistoric Rib/100/-300/Arch/Prehistoric Rib/Little gouge marks on the side suggest that this rib was someone's dinner./Item 1 289/Farm .01")
Item.create!(item_key: 584, information: "Prehistoric Vertebra/100/-300/Arch/Prehistoric Vertebra/A segment of some prehistoric creature's spine./Item 1 289/BusStop .01")
Item.create!(item_key: 585, information: "Skeletal Tail/100/-300/Arch/Skeletal Tail/It's pretty short for a tail./Item 1 289/UndergroundMine .01")
Item.create!(item_key: 586, information: "Nautilus Fossil/80/-300/Arch/Nautilus Fossil/This must've washed up ages ago from an ancient coral reef. /Item 1 289/Beach .03")
Item.create!(item_key: 587, information: "Amphibian Fossil/150/-300/Arch/Amphibian Fossil/The relatively short hind legs suggest some kind of primordial toad./Item 1 289/Forest .01 Mountain .01")
Item.create!(item_key: 588, information: "Palm Fossil/100/-300/Arch/Palm Fossil/Palm Fossils are relatively common, but this happens to be a particularly well-preserved specimen./Item 1 289/Desert .1 Beach .01 Forest .01")
Item.create!(item_key: 589, information: "Trilobite/50/-300/Arch/Trilobite/A long extinct relative of the crab./Item 1 289/Beach .03 Mountain .03 Forest .03")
Item.create!(item_key: 590, information: "Artifact Spot/0/-300/asdf/Artifact Spot/Uh... how did you get this in your inventory? Ape made a booboo./Item 1 289/Beach .03 Mountain .03 Forest .03")
Item.create!(item_key: 591, information: "Tulip/30/18/Basic -80/Tulip/The most popular spring flower. Has a very faint sweet smell.")
Item.create!(item_key: 593, information: "Summer Spangle/90/18/Basic -80/Summer Spangle/A tropical bloom that thrives in the humid summer air. Has a sweet, tangy aroma.")
Item.create!(item_key: 595, information: "Fairy Rose/290/18/Basic -80/Fairy Rose/An old folk legend suggests that the sweet smell of this flower attracts fairies.")
Item.create!(item_key: 597, information: "Blue Jazz/50/18/Basic -80/Blue Jazz/The flower grows in a sphere to invite as many butterflies as possible.")
Item.create!(item_key: 599, information: "Sprinkler/100/-300/Crafting -8/Sprinkler/Waters the 4 adjacent tiles every morning.")
Item.create!(item_key: 604, information: "Plum Pudding/260/70/Cooking -7/Plum Pudding/A traditional holiday treat./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 605, information: "Artichoke Dip/210/40/Cooking -7/Artichoke Dip/It's cool and refreshing./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 606, information: "Stir Fry/335/80/Cooking -7/Stir Fry/Julienned vegetables on a bed of rice./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 607, information: "Roasted Hazelnuts/270/70/Cooking -7/Roasted Hazelnuts/The roasting process creates a rich forest flavor./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 608, information: "Pumpkin Pie/385/90/Cooking -7/Pumpkin Pie/Silky pumpkin cream in a flakey crust./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 609, information: "Radish Salad/300/80/Cooking -7/Radish Salad/The radishes are so crisp!/food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 610, information: "Fruit Salad/450/105/Cooking -7/Fruit Salad/A delicious combination of summer fruits./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 611, information: "Blackberry Cobbler/260/70/Cooking -7/Blackberry Cobbler/There's nothing quite like it./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 612, information: "Cranberry Candy/175/50/Cooking -7/Cranberry Candy/It's sweet enough to mask the bitter fruit./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 613, information: "Apple/100/15/Basic -79/Apple/A crisp fruit used for juice and cider.")
Item.create!(item_key: 618, information: "Bruschetta/210/45/Cooking -7/Bruschetta/Roasted tomatoes on a crisp white bread./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 621, information: "Quality Sprinkler/450/-300/Crafting -8/Quality Sprinkler/Waters the 8 adjacent tiles every morning.")
Item.create!(item_key: 628, information: "Cherry Sapling/850/-300/Basic -74/Cherry Sapling/Takes 28 days to produce a mature cherry tree. Bears fruit in the spring. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 629, information: "Apricot Sapling/500/-300/Basic -74/Apricot Sapling/Takes 28 days to produce a mature Apricot tree. Bears fruit in the spring. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 630, information: "Orange Sapling/1000/-300/Basic -74/Orange Sapling/Takes 28 days to produce a mature Orange tree. Bears fruit in the summer. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 631, information: "Peach Sapling/1500/-300/Basic -74/Peach Sapling/Takes 28 days to produce a mature Peach tree. Bears fruit in the summer. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 632, information: "Pomegranate Sapling/1500/-300/Basic -74/Pomegranate Sapling/Takes 28 days to produce a mature Pomegranate tree. Bears fruit in the fall. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 633, information: "Apple Sapling/1000/-300/Basic -74/Apple Sapling/Takes 28 days to produce a mature Apple tree. Bears fruit in the fall. Only grows if the 8 surrounding \"tiles\" are empty.")
Item.create!(item_key: 634, information: "Apricot/50/15/Basic -79/Apricot/A tender little fruit with a rock-hard pit.")
Item.create!(item_key: 635, information: "Orange/100/15/Basic -79/Orange/Juicy, tangy, and bursting with sweet summer aroma.")
Item.create!(item_key: 636, information: "Peach/140/15/Basic -79/Peach/It's almost fuzzy to the touch.")
Item.create!(item_key: 637, information: "Pomegranate/140/15/Basic -79/Pomegranate/Within the fruit are clusters of juicy seeds.")
Item.create!(item_key: 638, information: "Cherry/80/15/Basic -79/Cherry/It's popular, and ripens sooner than most other fruits.")
Item.create!(item_key: 645, information: "Iridium Sprinkler/1000/-300/Crafting -8/Iridium Sprinkler/Waters the 24 adjacent tiles every morning.")
Item.create!(item_key: 648, information: "Coleslaw/345/85/Cooking -7/Coleslaw/It's light, fresh and very healthy./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 649, information: "Fiddlehead Risotto/350/90/Cooking -7/Fiddlehead Risotto/A creamy rice dish served with sauteed fern heads. It's a little bland./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 651, information: "Poppyseed Muffin/250/60/Cooking -7/Poppyseed Muffin/It has a soothing effect./food/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 668, information: "Stone/0/15/Basic/Stone/There's stone ore in this stone.")
Item.create!(item_key: 670, information: "Stone/0/15/Basic/Stone/There's stone ore in this stone.")
Item.create!(item_key: 674, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 675, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 676, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 677, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 678, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 679, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 680, information: "Green Slime Egg/1000/-300/Basic/Green Slime Egg/Can be hatched in a slime incubator.")
Item.create!(item_key: 681, information: "Rain Totem/20/-300/Crafting/Rain Totem/Activate to greatly increase the chance for rain tomorrow. Consumed on use.")
Item.create!(item_key: 682, information: "Mutant Carp/1000/10/Fish -4/Mutant Carp/The strange waters of the sewer turned this carp into a monstrosity./Day^Spring Summer")
Item.create!(item_key: 684, information: "Bug Meat/8/-300/Basic -28/Bug Meat/It's a juicy wad of bug flesh.")
Item.create!(item_key: 685, information: "Bait/1/-300/Basic -21/Bait/Causes fish to bite faster. Must first be attached to a fishing rod.")
Item.create!(item_key: 686, information: "Spinner/250/-300/Basic -22/Spinner/The shape makes it spin around in the water. Slightly increases the bite-rate when fishing.")
Item.create!(item_key: 687, information: "Dressed Spinner/500/-300/Basic -22/Dressed Spinner/The metal tab and colorful streamers create an enticing spectacle for fish. Increases the bite-rate when fishing.")
Item.create!(item_key: 688, information: "Warp Totem: Farm/20/-300/Crafting/Warp Totem: Farm/Warp directly to your house. Consumed on use.")
Item.create!(item_key: 689, information: "Warp Totem: Mountains/20/-300/Crafting/Warp Totem: Mountains/Warp directly to the mountains. Consumed on use.")
Item.create!(item_key: 690, information: "Warp Totem: Beach/20/-300/Crafting/Warp Totem: Beach/Warp directly to the beach. Consumed on use.")
Item.create!(item_key: 691, information: "Barbed Hook/500/-300/Basic -22/Barbed Hook/Makes your catch more secure, causing the \"fishing bar\" to cling to your catch. Works best on slow, weak fish.")
Item.create!(item_key: 692, information: "Lead Bobber/150/-300/Basic -22/Lead Bobber/Adds weight to your \"fishing bar\", preventing it from bouncing along the bottom.")
Item.create!(item_key: 693, information: "Treasure Hunter/250/-300/Basic -22/Treasure Hunter/Fish don't escape while collecting treasures. Also slightly increases the chance to find treasures.")
Item.create!(item_key: 694, information: "Trap Bobber/200/-300/Basic -22/Trap Bobber/Causes fish to escape slower when you aren't reeling them in.")
Item.create!(item_key: 695, information: "Cork Bobber/250/-300/Basic -22/Cork Bobber/Slightly increases the size of your \"fishing bar\".")
Item.create!(item_key: 698, information: "Sturgeon/200/10/Fish -4/Sturgeon/An ancient bottom-feeder with a dwindling population. Females can live up to 150 years./Day^Spring Summer")
Item.create!(item_key: 699, information: "Tiger Trout/150/10/Fish -4/Tiger Trout/A rare hybrid trout that cannot bear offspring of its own./Day^Spring Summer")
Item.create!(item_key: 700, information: "Bullhead/75/10/Fish -4/Bullhead/A relative of the catfish that eats a variety of foods off the lake bottom./Day^Spring Summer")
Item.create!(item_key: 701, information: "Tilapia/75/10/Fish -4/Tilapia/A primarily vegetarian fish that prefers warm water./Day^Spring Summer")
Item.create!(item_key: 702, information: "Chub/50/10/Fish -4/Chub/A common freshwater fish known for its voracious appetite./Day^Spring Summer")
Item.create!(item_key: 703, information: "Magnet/15/-300/Basic -21/Magnet/Increases the chance of finding treasures when fishing. However, fish aren't crazy about the taste.")
Item.create!(item_key: 704, information: "Dorado/100/10/Fish -4/Dorado/A fierce carnivore with brilliant orange scales./Day^Summer")
Item.create!(item_key: 705, information: "Albacore/75/10/Fish -4/Albacore/Prefers temperature \"edges\" where cool and warm water meet./Day^Spring Fall")
Item.create!(item_key: 706, information: "Shad/60/10/Fish -4/Shad/Lives in a school at sea, but returns to the rivers to spawn./Day^Spring Summer Fall")
Item.create!(item_key: 707, information: "Lingcod/120/10/Fish -4/Lingcod/A fearsome predator that will eat almost anything it can cram into its mouth./Day^Fall")
Item.create!(item_key: 708, information: "Halibut/80/10/Fish -4/Halibut/A flat fish that lives on the ocean floor./Day^Spring Summer")
Item.create!(item_key: 709, information: "Hardwood/15/-300/Basic -16/Hardwood/A special kind of wood with superior strength and beauty.")
Item.create!(item_key: 710, information: "Crab Pot/50/-300/Crafting/Crab Pot/Place it in the water, load it with bait, and check the next day to see if you've caught anything. Works in streams, lakes, and the ocean.")
Item.create!(item_key: 715, information: "Lobster/120/-300/Fish -4/Lobster/A large ocean-dwelling crustacean with a strong tail./Day^Spring Summer")
Item.create!(item_key: 716, information: "Crayfish/75/-300/Fish -4/Crayfish/A small freshwater relative of the lobster./Day^Spring Summer")
Item.create!(item_key: 717, information: "Crab/100/-300/Fish -4/Crab/A marine crustacean with two powerful pincers./Day^Spring Summer")
Item.create!(item_key: 718, information: "Cockle/50/-300/Fish -4/Cockle/A common saltwater clam./Day^Spring Summer")
Item.create!(item_key: 719, information: "Mussel/30/-300/Fish -4/Mussel/A common bivalve that often lives in clusters./Day^Spring Summer")
Item.create!(item_key: 720, information: "Shrimp/60/-300/Fish -4/Shrimp/A scavenger that feeds off the ocean floor. Widely prized for its meat./Day^Spring Summer")
Item.create!(item_key: 721, information: "Snail/65/-300/Fish -4/Snail/A wide-ranging mollusc that lives in a spiral shell./Day^Spring Summer")
Item.create!(item_key: 722, information: "Periwinkle/20/-300/Fish -4/Periwinkle/A tiny freshwater snail that lives in a blue shell./Day^Spring Summer")
Item.create!(item_key: 723, information: "Oyster/40/-300/Fish -4/Oyster/Constantly filters water to find food. In the process, it removes dangerous toxins from the environment./Day^Spring Summer")
Item.create!(item_key: 724, information: "Maple Syrup/200/20/Basic -27/Maple Syrup/A sweet syrup with a unique flavor./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 725, information: "Oak Resin/150/-300/Basic -27/Oak Resin/A sticky, fragrant substance derived from oak sap.")
Item.create!(item_key: 726, information: "Pine Tar/100/-300/Basic -27/Pine Tar/A pungent substance derived from pine sap.")
Item.create!(item_key: 727, information: "Chowder/135/90/Cooking -7/Chowder/A perfect way to warm yourself after a cold night at sea./food/0 1 0 0 0 0 0 0 0 0 0/1440")
Item.create!(item_key: 728, information: "Fish Stew/175/90/Cooking -7/Fish Stew/It smells a lot like the sea. Tastes better, though./food/0 3 0 0 0 0 0 0 0 0 0/1440")
Item.create!(item_key: 729, information: "Escargot/125/90/Cooking -7/Escargot/Butter-soaked snails cooked to perfection./food/0 2 0 0 0 0 0 0 0 0 0/1440")
Item.create!(item_key: 730, information: "Lobster Bisque/205/90/Cooking -7/Lobster Bisque/This delicate soup is a secret family recipe of Willy's./food/0 3 0 0 0 0 0 50 0 0 0/1440")
Item.create!(item_key: 731, information: "Maple Bar/300/90/Cooking -7/Maple Bar/It's a sweet doughnut topped with a rich maple glaze./food/1 1 1 0 0 0 0 0 0 0 0/1440")
Item.create!(item_key: 732, information: "Crab Cakes/275/90/Cooking -7/Crab Cakes/Crab, bread crumbs, and egg formed into patties then fried to a golden brown./food/0 0 0 0 0 0 0 0 0 1 1/1440")
Item.create!(item_key: 734, information: "Woodskip/75/10/Fish -4/Woodskip/A very sensitive fish that can only live in pools deep in the forest./Day^Spring Summer")
Item.create!(item_key: 745, information: "Strawberry Seeds/0/-300/Seeds -74/Strawberry Seeds/Plant these in spring. Takes 8 days to mature, and keeps producing strawberries after that.")
Item.create!(item_key: 746, information: "Jack-O-Lantern/0/-300/Crafting -8/Jack-O-Lantern/A whimsical fall decoration.")
Item.create!(item_key: 747, information: "Rotten Plant/0/-300/Basic -20/Rotten Plant/Decomposing organic material. It's slimy and unpleasant.")
Item.create!(item_key: 748, information: "Rotten Plant/0/-300/Basic -20/Rotten Plant/Decomposing organic material. It's slimy and unpleasant.")
Item.create!(item_key: 749, information: "Omni Geode/0/-300/Basic/Omni Geode/A blacksmith can break this open for you. These geodes contain a wide variety of Minerals./538 542 548 549 552 555 556 557 558 566 568 569 571 574 576 541 544 545 546 550 551 559 560 561 564 567 572 573 577 539 540 543 547 553 554 562 563 565 570 575 578 121 122 123")
Item.create!(item_key: 750, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 751, information: "Stone/0/15/Basic/Stone/There's copper ore in this stone.")
Item.create!(item_key: 760, information: "Stone/0/15/Basic/Stone/...")
Item.create!(item_key: 762, information: "Stone/0/15/Basic/Stone/...")
Item.create!(item_key: 764, information: "Stone/0/15/Basic/Stone/gold ore")
Item.create!(item_key: 765, information: "Stone/0/15/Basic/Stone/iridium ore")
Item.create!(item_key: 766, information: "Slime/5/-300/Basic -28/Slime/A shimmering, gelatinous glob with no smell.")
Item.create!(item_key: 767, information: "Bat Wing/15/-300/Basic -28/Bat Wing/The material is surprisingly delicate.")
Item.create!(item_key: 768, information: "Solar Essence/40/-300/Basic -28/Solar Essence/The glowing face is warm to the touch.")
Item.create!(item_key: 769, information: "Void Essence/50/-300/Basic -28/Void Essence/It's quivering with dark energy.")
Item.create!(item_key: 770, information: "Mixed Seeds/0/-300/Seeds -74/Mixed Seeds/There's a little bit of everything here. Plant them and see what grows!")
Item.create!(item_key: 771, information: "Fiber/1/-300/Basic -16/Fiber/Raw material sourced from plants.")
Item.create!(item_key: 772, information: "Oil of Garlic/1000/80/Cooking -7/Oil of Garlic/Drink this and weaker monsters will avoid you./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 773, information: "Life Elixir/500/80/Cooking -7/Life Elixir/Restores health to full./drink/0 0 0 0 0 0 0 0 0 0 0/0")
Item.create!(item_key: 774, information: "Wild Bait/15/-300/Basic -21/Wild Bait/A unique recipe from Linus. It appeals to all fish.")
Item.create!(item_key: 775, information: "Glacierfish/1000/10/Fish -4/Glacierfish/Builds a nest on the underside of glaciers./Day^Winter")
Item.create!(item_key: 784, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 785, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 786, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 787, information: "Battery Pack/500/-300/Basic -16/Battery Pack/It's fully charged with precious energy.")
Item.create!(item_key: 788, information: "Lost Axe/0/-300/Quest/Lost Axe/Robin's been looking everywhere for it.")
Item.create!(item_key: 789, information: "Lucky Purple Shorts/0/-300/Quest/Lucky Purple Shorts/Better not inspect these too closely.")
Item.create!(item_key: 790, information: "Berry Basket/0/-300/Quest/Berry Basket/The fibers are stained with berry juice.")
Item.create!(item_key: 792, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 793, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 794, information: "Weeds/0/15/Basic/Weeds/Ugly weeds.")
Item.create!(item_key: 795, information: "Void Salmon/150/25/Fish -4/Void Salmon/A salmon, twisted by void energy. The fresh meat is jet black, but rapidly turns pink when exposed to air./Day^Spring Summer")
Item.create!(item_key: 796, information: "Slimejack/100/15/Fish -4/Slimejack/He's coated in a very thick layer of slime. He keeps slipping out of your hands!/Day^Spring Summer")

puts "Calendar: #{Calendar.count}"